// footer
const currentYear = new Date().getFullYear();
document.querySelector("#year").innerHTML = currentYear;

const topics = [
    "What's your favorite way to spend a weekend?",
    "What's the best meal you've cooked recently?",
    "Do you prefer mornings or evenings? Why?",
    "What's one habit you're trying to build?",
    "What's your go-to way to relax after a long day?",
    "Do you enjoy working out? What's your favorite exercise?",
    "What's your favorite kind of weather?",
    "Do you prefer tea or coffee? Why?",
    "What's the best thing that happened to you today?",
    "What does your ideal vacation look like?",
    "Do you enjoy reading? What's your favorite book?",
    "What's your favorite type of music or artist?",
    "Do you play any instruments?",
    "What's your favorite board or video game?",
    "Have you ever tried a creative hobby like painting or writing?",
    "What's your favorite sport to play or watch?",
    "Are you a collector of anything?",
    "Do you enjoy photography? What's your favorite subject to photograph?",
    "Do you like gardening or growing plants?",
    "What's a hobby you'd like to learn someday?",
    "What's your favorite type of cuisine?",
    "What's a dish you want to learn how to cook?",
    "Do you prefer sweet or savory snacks?",
    "What's the best dessert you've ever had?",
    "What's your favorite childhood snack?",
    "Do you enjoy trying new restaurants or sticking to favorites?",
    "What's your favorite street food?",
    "Do you have a favorite holiday dish?",
    "What's your comfort food?",
    "Have you ever tried a food from another culture that surprised you?",
    "What's your dream travel destination?",
    "Have you ever traveled abroad? Where?",
    "Do you prefer beach vacations or mountain retreats?",
    "What's the most interesting place you've ever visited?",
    "Have you ever had a travel mishap?",
    "What's a city you'd love to explore?",
    "Do you prefer solo trips or traveling with friends/family?",
    "What's a local destination you recommend to others?",
    "Do you like road trips? What's your favorite route?",
    "Have you ever tried adventure activities while traveling?",
    "What's a skill you've recently learned?",
    "What's a personal goal you're working on?",
    "Do you enjoy learning new languages?",
    "What's the best piece of advice you've ever received?",
    "What's your favorite childhood memory?",
    "What's a mistake you learned a lot from?",
    "Who is someone you admire and why?",
    "What's a book, video, or podcast that inspired you?",
    "What motivates you to keep growing as a person?",
    "If you could study anything for free, what would it be?",
    "If you could invent something, what would it be?",
    "What's a fictional universe you'd love to live in?",
    "If you could be any animal, what would you be?",
    "What's your idea of a perfect day?",
    "If you had unlimited resources, what kind of project would you start?",
    "What superpower would you choose and why?",
    "What's your favorite childhood fantasy or dream?",
    "If you could write a book, what would it be about?",
    "What's a movie plot you'd rewrite?",
    "If you could design your own dream home, what would it include?",
    "What's a cause you're passionate about?",
    "How do you like to stay informed about world events?",
    "What's a global issue you'd love to help solve?",
    "What's a cultural festival you'd like to attend?",
    "Do you enjoy volunteering? What's your experience?",
    "What's a tradition or custom you find fascinating?",
    "How do you celebrate holidays in your family?",
    "What's your favorite way to give back to your community?",
    "Have you ever participated in a charity event?",
    "What's something you admire about another culture?",
    "What's your favorite memory with a friend or family member?",
    "What qualities do you value most in a friend?",
    "Who has had the biggest influence on your life?",
    "What's your favorite way to spend time with loved ones?",
    "Do you have a funny or embarrassing story about your childhood?",
    "What's the best advice a family member gave you?",
    "How do you show appreciation for others?",
    "What's your go-to way to cheer someone up?",
    "Do you believe in soulmates?",
    "What's a lesson you've learned from a past relationship?",
    "What's a recent technological advancement that excites you?",
    "Do you enjoy exploring space-related topics?",
    "What's your favorite gadget or app?",
    "How do you think AI will change the world?",
    "What's a scientific discovery that fascinates you?",
    "Are you more interested in biology, physics, or chemistry?",
    "What's the coolest experiment you've ever seen or done?",
    "How do you use technology in your daily life?",
    "What's your opinion on self-driving cars?",
    "Do you think technology makes life easier or harder?",
    "What's a fun fact you recently learned?",
    "What's a quote that inspires you?",
    "Do you believe in luck or fate?",
    "What's your favorite childhood cartoon or show?",
    "Have you ever had a strange coincidence happen to you?",
    "What's something unusual or unique about you?",
    "Do you prefer big cities or small towns? Why?",
    "What's an unusual job or career you'd love to try?",
    "If you could time travel, where and when would you go?",
    "What's one question you wish people would ask you more often?", 
    "If you were a fruit, what kind of fruit would you be and why?",
    "What's the weirdest food combination you've ever tried?",
    "If animals could talk, which one would be the most sarcastic?",
    "What's the most useless talent you have?",
    "If you could only eat one food for the rest of your life, what would it be?",
    "What's the weirdest dream you've ever had?",
    "If you could instantly master any skill, what would it be?",
    "What’s the most awkward thing you’ve ever done in public?",
    "If you were invisible for a day, what would you do?",
    "What's your favorite conspiracy theory (even if you don't believe it)?",
    "What’s the most embarrassing song in your playlist?",
    "If you were stranded on an island, which three items would you bring?",
    "Do you think aliens exist? Why or why not?",
    "If you were a superhero, what would your name and power be?",
    "What's the funniest prank you've ever pulled on someone?",
    "Do you believe pineapple belongs on pizza?",
    "What’s your guilty pleasure TV show or movie?",
    "If you could swap lives with a celebrity for one day, who would it be?",
    "What’s the most ridiculous argument you've ever had?",
    "If you could have any animal as a pet, real or fictional, what would it be?",
    "What’s the weirdest thing you’ve ever Googled?",
    "Do you fold or scrunch your toilet paper?",
    "If you could rename yourself, what name would you choose?",
    "What’s the worst haircut you’ve ever had?",
    "If you could live in any historical era, which one would you choose?",
    "What’s your most irrational fear?",
    "Have you ever accidentally sent a text to the wrong person? What happened?",
    "If you could teleport anywhere right now, where would you go?",
    "What’s the strangest compliment you’ve ever received?",
    "If you could turn into any object for a day, what would it be?",
    "What’s the most bizarre fact you know?",
    "If your life were a movie, what genre would it be?",
    "Do you believe in ghosts or spirits?",
    "What’s the most random thing you’ve ever memorized?",
    "If you could make one rule everyone in the world had to follow, what would it be?",
    "If you had to speak in only movie quotes for a day, what would you say?",
    "What’s the silliest thing you’ve cried over?",
    "If you were a flavor, what would you be?",
    "What’s the strangest thing you’ve seen someone do in public?",
    "If you could switch places with any fictional character, who would it be?",
    "What’s the weirdest thing you believed as a kid?",
    "What’s your go-to karaoke song?",
    "What’s the funniest name you could give a pet?",
    "If you were a potato, how would you want to be cooked?",
    "What’s something totally random you’ve always wanted to try?",
    "What’s your favorite knock-knock joke?",
    "If you could live in any cartoon, which one would it be?",
    "What’s the dumbest way you’ve hurt yourself?",
    "What’s your favorite “dad joke”?",
    "If you could be any mythical creature, which one would you pick?",
    "Have you ever laughed at the wrong moment?",
    "If your pet could talk, what do you think they’d say about you?",
    "What’s a made-up holiday you think should exist?",
    "If you had to eat a crayon, what color would you choose?",
    "What’s the funniest misunderstanding you’ve ever had?",
    "If you could shrink anything in the world and keep it as a pet, what would it be?",
    "What’s the worst advice you’ve ever received?",
    "If you were a meme, what would your caption be?",
    "What’s the funniest or weirdest thing you've ever overheard?",
    "If you could only wear one color for the rest of your life, what would it be?",
    "What’s the most out-of-character thing you’ve ever done?",
    "If you were a villain, what would your evil plan be?",
    "What’s the most awkward autocorrect fail you’ve experienced?",
    "If you could erase one food from existence, what would it be?",
    "What’s the strangest thing you’ve ever eaten?",
    "If you could host your own talk show, who would your first guest be?",
    "What’s the weirdest rule you’ve ever had to follow?",
    "What’s something people always misunderstand about you?",
    "If you could bring one extinct animal back to life, which one would it be?",
    "What’s your favorite weird sound effect?",
    "If you could change your voice to sound like anyone, who would it be?",
    "What’s the most ridiculous fear you’ve ever heard of?",
    "If you could design a new emoji, what would it look like?",
    "What’s the strangest app on your phone?",
    "What’s the silliest superstition you’ve ever followed?",
    "If you could be in a video game, which one would you pick?",
    "What’s the weirdest rumor you’ve heard about yourself?",
    "If you were a dessert, what would you be?",
    "What’s the oddest thing you’ve seen on the internet?",
    "What’s a skill you wish you could learn instantly?",
    "If you could live inside a book, which one would it be?",
    "What’s the funniest thing you’ve seen a stranger do?",
    "If you could make an inanimate object talk, which one would it be?",
    "What’s a talent you don’t have but wish you did?",
    "What’s your least favorite chore and why?",
    "If you could trade places with your pet for a day, what would you do?",
    "What’s the most unnecessary thing you’ve ever bought?",
    "If you could create a new animal hybrid, what would it be?",
    "What’s your favorite type of cheese?",
    "What’s the strangest text message you’ve received?",
    "If you could have a theme song play every time you entered a room, what would it be?",
    "What’s the most ridiculous thing you’ve done out of boredom?",
    "If you could invent a new flavor of ice cream, what would it be?",
    "What’s the most random thing you’ve shouted in public?",
    "If you could give yourself a new middle name, what would it be?",
    "What’s your go-to excuse when you’re late?",
    "If you were a smell, what would it be?",
    "What’s the funniest autocorrect fail you’ve had?",
    "If you could live inside a video game for a week, which one would you pick?",
    "What’s the weirdest way you’ve made a friend?",
    "What’s the funniest animal video you’ve seen recently?",
    "If you could make a new law, what would it be?",
    "What’s a joke that never gets old?",
    "What's the worst movie you’ve ever seen?", 
    "If you could be any flavor of ice cream, what would you be?",
    "What’s the most random thing you’ve ever said out loud?",
    "If you could have a magical backpack, what would it always contain?",
    "What’s the funniest misheard song lyric you’ve encountered?",
    "If you had to name a new planet, what would you call it?",
    "What’s the most useless object you own but can’t throw away?",
    "If you could replace your alarm clock sound with anything, what would it be?",
    "What’s the silliest superstition you secretly follow?",
    "If you could have a pet that fits in your pocket, what would it be?",
    "What’s the weirdest thing you’ve ever seen in a store?",
    "If you could only eat desserts for a month, which ones would you pick?",
    "What’s your favorite way to make someone laugh?",
    "If you could create a new board game, what would it be about?",
    "What’s the most bizarre outfit you’ve seen someone wear?",
    "If you could give yourself a superhero catchphrase, what would it be?",
    "What’s the funniest thing you’ve accidentally broken?",
    "If you could have a sandwich named after you, what would be in it?",
    "What’s the most awkward situation you’ve laughed in?",
    "If you were turned into a cartoon animal, which one would you be?",
    "What’s the weirdest dream you’ve had that you still remember?",
    "If you could make a movie about your life, what would the title be?",
    "What’s the most random thing you’ve ever done in public?",
    "If you could only eat food from one country for the rest of your life, which one?",
    "What’s the most creative excuse you’ve used to get out of something?",
    "If you could be a character in any video game, who would it be?",
    "What’s your go-to party trick or talent?",
    "If you could have a pet made entirely of candy, what would it look like?",
    "What’s the strangest thing you’ve ever bought online?",
    "If you could instantly become great at a ridiculous sport, which one would it be?",
    "What’s the weirdest compliment you’ve ever received?",
    "If you had a secret bunker, what fun thing would you put inside it?",
    "What’s the most unnecessary gadget you wish existed?",
    "If you could create a new public holiday, what would it celebrate?",
    "What’s the most ridiculous food invention you’d like to try?",
    "If you could have an unlimited supply of one silly item, what would it be?",
    "What’s your favorite kind of accidental comedy?",
    "If you could only wear clothes of one ridiculous theme forever, what theme?",
    "What’s the funniest story someone’s told you?",
    "If you were a mythical creature, what strange power would you have?",
    "What’s the weirdest thing you’ve overheard in a conversation?",
    "If you could live inside a video game world, which one would it be?",
    "What’s the silliest fear you had as a kid?",
    "If you could be any character in a TV show, who would you be?",
    "What’s the funniest reason you’ve gotten in trouble?",
    "If you could own a magical vehicle, what would it do?",
    "What’s the funniest item you’ve found at a thrift store?",
    "If you could write a sitcom, what would the plot be?",
    "What’s the most ridiculous misunderstanding you’ve been part of?",
    "If you could have a party with any fictional characters, who would you invite?",
    "What’s the weirdest prank you’ve witnessed?",
    "If you could only drink one weird-flavored soda forever, what flavor?",
    "What’s your favorite unexpected food combination?",
    "If you could instantly learn a silly dance move, what would it be?",
    "What’s the funniest way you’ve reacted to a surprise?",
    "If you could name a volcano, what would you call it?",
    "What’s the oddest thing you’ve ever collected?",
    "If you could trade lives with an animal for a day, which one would it be?",
    "What’s your favorite animal noise to imitate?",
    "If you could create your own emoji, what would it look like?",
    "What’s the strangest weather you’ve ever experienced?",
    "If you could shrink one object to carry around, what would it be?",
    "What’s the weirdest thing you’ve accidentally stepped on?",
    "If you could make a harmless prank world-famous, what would it be?",
    "What’s the silliest advice you’ve ever received?",
    "If you could replace your laugh with a sound effect, what would it be?",
    "What’s the most random object you’d bring to a desert island?",
    "If you could design a silly app, what would it do?",
    "What’s the weirdest talent you’ve seen someone have?",
    "If you could give any animal a funny hat, which one and why?",
    "What’s your favorite memory of something going hilariously wrong?", 
    "If you could create a new ice cream topping, what would it be?",
    "What’s the funniest name you’d give a racehorse?",
    "If you could turn any object into a musical instrument, what would it be?",
    "What’s the weirdest thing you’ve seen someone eat?",
    "If you could invent a new dance move, what would it be called?",
    "What’s the most embarrassing thing you’ve done on a dare?",
    "If you could make one animal much smaller, which one and why?",
    "What’s your favorite useless life hack?",
    "If you had a time machine that only went backwards, what era would you visit?",
    "What’s the funniest sound you’ve ever heard?",
    "If you were a condiment, which one would you be and why?",
    "What’s the most bizarre pet name you’ve ever heard?",
    "If you could create your own candy, what flavor would it be?",
    "What’s the funniest way you’ve misread something?",
    "If you could trade voices with a cartoon character, who would it be?",
    "What’s the most random trivia fact you know?",
    "If you could make a cloud in any shape, what would it look like?",
    "What’s the weirdest thing you’ve forgotten and remembered later?",
    "If you could write a song about your daily life, what genre would it be?",
    "What’s the most creative insult you’ve ever heard?",
    "If you could rename any city, what new name would you give it?",
    "What’s the funniest animal behavior you’ve ever seen?",
    "If you could design a themed hotel, what theme would it be?",
    "What’s the strangest thing you’ve seen someone carry?",
    "If you could build a secret passage in your house, where would it go?",
    "What’s the most ridiculous goal you’ve set for yourself?",
    "If you could add one silly law to the world, what would it be?",
    "What’s the weirdest way you’ve celebrated a holiday?",
    "If you were a cereal, what would you be called?",
    "What’s the most hilarious typo you’ve ever made?",
    "If you could turn any fruit into a mode of transportation, which one?",
    "What’s the oddest thing you’ve seen someone wear in public?",
    "If you could only speak in rhymes for a day, how would it go?",
    "What’s the funniest custom or tradition you’ve ever heard of?",
    "If you could create a new mythical creature, what would it be like?",
    "What’s the funniest nickname you’ve ever had?",
    "If you could turn any boring task into a fun game, what would it be?",
    "What’s the weirdest thing you’ve ever Googled in a panic?",
    "If you could make one item of clothing illegal, what would it be?",
    "What’s the funniest excuse you’ve heard someone use?",
    "If you could invent a new holiday, what quirky traditions would it have?",
    "What’s the silliest text message you’ve received?",
    "If you could bring back one outdated fashion trend, which one?",
    "What’s the most awkward misunderstanding you’ve ever been involved in?",
    "If you could make a parody of any movie, what would it be about?",
    "What’s the most absurd thing you’ve seen someone do to win a bet?",
    "If you could change the sound your footsteps make, what would it be?",
    "What’s the most ridiculous title for a movie you could come up with?",
    "If you could make an animal as big as a car, which one would it be?",
    "What’s the funniest moment you’ve seen on live TV?",
    "If you could add a silly new rule to a sport, what would it be?",
    "What’s the weirdest way you’ve tried to make money?",
    "If you could create a board game based on your life, what would it include?",
    "What’s the most ridiculous thing you’ve ever believed as a kid?",
    "If you could turn your favorite snack into a building material, what would you build?",
    "What’s the silliest thing you’ve argued about with a friend?",
    "If you had to communicate only with gestures for a day, how would it go?",
    "What’s the strangest way you’ve seen someone solve a problem?",
    "If you could live in a world where one funny law existed, what would it be?",
    "What’s the funniest or most creative way you’ve ever answered a question?",
    "If you could put googly eyes on one thing, what would it be?",
    "What’s the most unusual name you’ve ever heard for a pet or object?",
    "If you had to invent a new pasta shape, what would it look like?",
    "What’s the weirdest dream you’ve had involving food?",
    "If you were a drink, what would your ingredients be?",
    "What’s the funniest way you’ve seen someone fail at multitasking?",
    "If you could create a reality TV show about something silly, what would it be?",
    "What’s the most bizarre text or email you’ve accidentally sent?", 
    "If you could replace your alarm clock sound with something ridiculous, what would it be?",
    "What’s the weirdest tradition your family has?",
    "If you could make any inanimate object alive for a day, what would you choose?",
    "What’s the funniest animal noise you can imitate?",
    "If you could invent a silly superpower, what would it be?",
    "What’s the strangest advice you’ve ever received?",
    "If you could give any animal a job, what would it be and why?",
    "What’s the oddest thing you’ve ever found in your pocket?",
    "If you had to live in a giant version of any toy, what would it be?",
    "What’s the most awkward text reply you’ve ever sent?",
    "If you could only eat food that starts with one letter, which letter would you pick?",
    "What’s the strangest sound you’ve ever heard in nature?",
    "If you had to rename all your favorite foods, what funny names would you give them?",
    "What’s the most hilarious misunderstanding you’ve witnessed?",
    "If you were stuck in a comedy movie, what role would you play?",
    "What’s the weirdest thing you’ve seen someone try to balance on their head?",
    "If you had to make a mascot for your favorite hobby, what would it look like?",
    "What’s the strangest place you’ve ever fallen asleep?",
    "If you could make any object smell like chocolate, what would it be?",
    "What’s the funniest nickname you’ve ever given someone?",
    "If you could combine two animals to make the ultimate funny creature, what would they be?",
    "What’s the most ridiculous game or sport you’ve ever invented?",
    "If you could put a funny face on any object, what would it be?",
    "What’s the weirdest song you’ve ever heard someone sing in public?",
    "If you could turn your favorite movie into a comedy, what changes would you make?",
    "What’s the silliest costume you’ve ever worn?",
    "If you had to name a pet after your favorite food, what would it be?",
    "What’s the strangest collection you’ve ever heard of?",
    "If you could turn any everyday activity into an Olympic sport, what would it be?",
    "What’s the most bizarre competition you’ve ever participated in or heard of?",
    "If you could invent a totally pointless gadget, what would it do?",
    "What’s the funniest misheard lyric you’ve ever sung?",
    "If you could create a parody of a famous song, what would the new title be?",
    "What’s the weirdest combination of toppings you’d put on a pizza?",
    "If you could live in a house shaped like any object, what would it be?",
    "What’s the oddest thing you’ve ever tried to fix with duct tape?",
    "If you had to wear one funny accessory for the rest of your life, what would it be?",
    "What’s the most creative excuse you’ve ever made up?",
    "If you could create a theme park ride about your life, what would it be like?",
    "What’s the funniest nickname someone has given you?",
    "If you could swap places with any piece of furniture, which one and why?",
    "What’s the most unusual skill you’ve ever seen someone demonstrate?",
    "If you had to pick a silly ringtone for your phone, what would it be?",
    "What’s the funniest mistake you’ve made in the kitchen?",
    "If you could live in any funny commercial, which one would you choose?",
    "What’s the most absurd story you’ve ever made up on the spot?",
    "If you had to replace all mirrors with something else, what would it be?",
    "What’s the strangest or funniest thing you’ve lost and found again?",
    "If you could design a ridiculously oversized object, what would it be?",
    "What’s the most laughable prediction you’ve ever made?",
    "If you could turn any job into a comedy sketch, which one would it be?",
    "What’s the most amusing way you’ve ever introduced yourself?",
    "If you could rename common household items to funny names, what would you pick?",
    "What’s the weirdest excuse you’ve heard for being late?",
    "If you had to wear socks with a crazy pattern every day, what would the pattern be?",
    "What’s the strangest thing you’ve ever seen someone carry on public transport?",
    "If you could turn any historical event into a comedy, which one would it be?",
    "What’s the funniest voice or accent you can do?",
    "If you could design a pillow with a funny feature, what would it do?",
    "What’s the most ridiculous outfit you’ve ever seen someone wear?",
    "If you could host a game show with a silly twist, what would the rules be?",
    "What’s the strangest thing you’ve ever taken a photo of?",
    "If you could add a silly hat to any famous statue, which one would it be?",
    "What’s the weirdest DIY project you’ve attempted?", 
    "If you could add a silly sound effect to any activity, what would it be?",
    "What’s the most ridiculous text message you’ve ever received?",
    "If you could make any wild animal tiny and keep it as a pet, what would you choose?",
    "What’s the funniest face you can make?",
    "If you could turn any building into a giant inflatable, which one would it be?",
    "What’s the strangest thing you’ve ever accidentally sat on?",
    "If you had to invent a holiday with a wacky tradition, what would it be?",
    "What’s the weirdest dream you can remember having?",
    "If you could make a parody of your favorite book, what would the title be?",
    "What’s the funniest name you’d give to a spaceship?",
    "If you could replace the sounds animals make with other noises, which ones would you pick?",
    "What’s the most absurd thing you’ve ever laughed uncontrollably at?",
    "If you could give yourself a superhero weakness, what would it be?",
    "What’s the weirdest thing you’ve ever eaten on a dare?",
    "If you had to pick a ridiculous mascot for your life, what would it be?",
    "What’s the funniest or weirdest thing you’ve found while cleaning?",
    "If you could turn any object into a musical instrument, what would it be?",
    "What’s the most laughable thing you’ve ever tried to explain to someone?",
    "If you had to perform a comedy routine about your life, what story would you tell first?",
    "What’s the silliest rumor you’ve ever heard about yourself?",
    "If you could create a new kind of sandwich with the strangest ingredients, what would it be?",
    "What’s the weirdest thing you’ve ever bought online?",
    "If you could replace gravity with something funny, what would it be?",
    "What’s the most unusual shape you’d want a cloud to be?",
    "If you could make any TV show into a comedy, which one would you pick?",
    "What’s the funniest animal video you’ve ever seen?",
    "If you could have a magical power that only works once a week, what would it be?",
    "What’s the most ridiculous invention you’ve ever heard of?",
    "If you had to walk everywhere in a funny way, what would it be?",
    "What’s the most hilarious typo you’ve ever made?",
    "If you could prank-call anyone in history, who would it be and why?",
    "What’s the funniest name you’d give a boat?",
    "If you could make up a silly law for a day, what would it be?",
    "What’s the most absurd thing you’ve ever seen someone wear?",
    "If you could swap roles with any cartoon character, who would it be?",
    "What’s the silliest dance move you’ve ever seen?",
    "If you could invent a wacky new sport, what would the rules be?",
    "What’s the most awkward question you’ve been asked?",
    "If you could replace your shadow with something funny, what would it look like?",
    "What’s the weirdest gift you’ve ever received?",
    "If you had to create a funny nickname for your pet, what would it be?",
    "What’s the most bizarre item you’ve ever seen for sale?",
    "If you could live in a house shaped like any food, what food would it be?",
    "What’s the funniest sound effect you’d add to an action movie?",
    "If you could only communicate using one sound for a day, what sound would it be?",
    "What’s the weirdest thing you’ve ever seen someone do at a party?",
    "If you had to design a silly amusement park ride, what would it be?",
    "What’s the strangest talent you’ve ever discovered about yourself?",
    "If you could wear any costume to work every day, what would it be?",
    "What’s the most hilarious voice impression you can do?",
    "If you could only wear shoes made of one weird material, what would it be?",
    "What’s the funniest miscommunication you’ve ever experienced?",
    "If you had to write a comedy sketch about your morning routine, what would it include?",
    "What’s the oddest item you’ve ever found in your fridge?",
    "If you could turn your laugh into a magical power, what would it do?",
    "What’s the funniest prank someone has pulled on you?",
    "If you had to wear a funny hat for the rest of your life, what kind would it be?",
    "What’s the most ridiculous thing you’ve ever accidentally spilled?",
    "If you could make a funny face emoji into a real-life mask, which one would it be?",
    "What’s the most absurd thing you’ve ever shouted during an argument?",
    "If you could turn a serious historical moment into a comedy movie, which one would it be?",
    "What’s the weirdest thing you’ve ever tripped over?",
    "If you had to make a comedy movie about a boring object, what would it be about?",
    "What’s the most hilarious misunderstanding you’ve ever had with a stranger?",
    "If you could replace your hair with something silly, what would it be?"   
];

let num = Math.floor(Math.random() * topics.length);

document.getElementById("topic").innerHTML = topics[num];


function generate() {
    num = Math.floor(Math.random() * topics.length);
    document.getElementById("topic").innerHTML = topics[num];
}